data <- read.table("household_power_consumption.txt", header=TRUE, sep=";", stringsAsFactors = FALSE, dec=".")
data <- data[data$Date %in% c("1/2/2007","2/2/2007"),]
sub1 <- as.numeric(data$Sub_metering_1)
sub2 <- as.numeric(data$Sub_metering_2)
sub3 <- as.numeric(data$Sub_metering_3)
plot(datetime, sub1, type="l", xlab="", ylab="Energy sub metering")
lines(datetime, sub2, type="l", xlab="", ylab="Energy sub metering", col=("red"))
lines(datetime, sub3, type="l", xlab="", ylab="Energy sub metering", col=("blue"))
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=2.5, col=c("black", "red", "blue"))
dev.copy(png,"plot3.png", width=480, height=480)
dev.off()